POST http://3.19.242.75:8000/api/authentication/signup 
Content-Type: application/json

{ "username": "sushrutDiwan", "password": "Pass1234!", "email": "sushrut.diwan.sd@gmail.com" }

###

POST http://3.19.242.75:8000/api/authentication/login  
Content-Type: application/json

{ "username": "adi", "password": "Pass1234!" }

###

GET http://3.19.242.75:8000/api/authentication/testtoken 
Content-Type: application/json 
Authorization: Token f968d76400d70a1865e7bf4648debd41b843a08d


###

GET http://3.19.242.75:8000/api/category-list/
Content-Type: application/json 
Authorization: Token f968d76400d70a1865e7bf4648debd41b843a08d

###

GET http://3.19.242.75:8000/api/item-list/
Content-Type: application/json 
Authorization: Token f968d76400d70a1865e7bf4648debd41b843a08d

###

GET http://127.0.0.1:8000/api/item-list/?page=1
Content-Type: application/json 
Authorization: Token f968d76400d70a1865e7bf4648debd41b843a08d

###
GET http://3.19.242.75:8000/api/item-detail/?SKU=XYZTA
Content-Type: application/json 
Authorization: Token 989ac80c336085e648e00f5c269b9554658bc838

###

POST http://3.19.242.75:8000/api/item-create/
Content-Type: application/json 
Authorization: Token 989ac80c336085e648e00f5c269b9554658bc838

{
    "SKU": "ASDFEW",
    "name": "Item11",
    "category": "test1",
    "tags": "test",
    "stock_status": "Out of Stock",
    "available_stock": 10
}

###

POST http://127.0.0.1:8000/api/item-create/
Content-Type: application/json 
Authorization: Token 989ac80c336085e648e00f5c269b9554658bc838

{
    "SKU": "ASDOTNE",
    "name": "Item",
    "category": "test1",
    "tags": "test",
    "stock_status": "In Stock",
    "available_stock": 10
}

###

POST http://3.19.242.75:8000/api/category-create/
Content-Type: application/json 
Authorization: Token 989ac80c336085e648e00f5c269b9554658bc838

{
    "name": "test2"
}

###

POST http://3.19.242.75:8000/api/item-update/?SKU=UYRHFG
Content-Type: application/json 
Authorization: Token 989ac80c336085e648e00f5c269b9554658bc838

{
    "SKU": "UYRHFG",
    "name": "item99",
    "category": "test1",
    "tags": "test",
    "stock_status": "In Stock",
    "available_stock": 1000
}

###

DELETE  http://3.19.242.75:8000/api/item-delete/?SKU=XYZTA
Content-Type: application/json 
Authorization: Token 989ac80c336085e648e00f5c269b9554658bc838

###

DELETE  http://3.19.242.75:8000/api/category-delete/?category=test1
Content-Type: application/json 
Authorization: Token 989ac80c336085e648e00f5c269b9554658bc838

###
POST http://127.0.0.1:8000/api/authentication/signup 
Content-Type: application/json

{ "username": "sushrutDiwan", "password": "Pass1234!", "email": "sushrut.diwan.sd@gmail.com" }

###

POST http://127.0.0.1:8000/api/authentication/login  
Content-Type: application/json

{ "username": "sushrutDiwan", "password": "newPassword" }

###

GET http://127.0.0.1:8000/api/authentication/testtoken 
Content-Type: application/json 
Authorization: Token f968d76400d70a1865e7bf4648debd41b843a08d


###

POST http://127.0.0.1:8000/api/authentication/forgot-password 
Content-Type: application/json

{ "email": "sushrut.diwan.sd@gmail.com" }

###

POST http://127.0.0.1:8000/api/authentication/reset-password/?uidEncoded=NQ&token=c2afmc-f62c49690c4f273c6abb0ddf25069513
Content-Type: application/json

{"new_password" : "newPassword" }
